# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-09 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, default='', max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('card_id', models.CharField(blank=True, default='', max_length=100)),
                ('info', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
