# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
